### ISSUE TITLE
Build script failure

### ISSUE THREAD

**Issue by ishuverma** [PatrickSteiner/IoT_Demo_Gateway#12]
Failure during:
-- Building docker-compose based images
Building smartgateway

Step 8 : RUN chown -R psteiner:psteiner $HOME
 ---> Running in 0591b77d0ef7
chown: invalid group: `psteiner:psteiner'
ERROR: Service 'smartgateway' failed to build: The command '/bin/sh -c chown -R psteiner:psteiner $HOME' returned a non-zero code: 1

**Comment by PatrickSteiner** [comment]
Should work now, changed the relevant parts in all Dockerfiles.
