### ISSUE TITLE
Service 'smartgateway' failed to build: repository [...] not found: does not exist or no pull access

### ISSUE THREAD

**Issue by mophahr** [PatrickSteiner/IoT_Demo_Gateway#23]
When running `# ./build.sh` I get the following error (full output can be found below):

`Building smartgateway
Step 1/16 : FROM psteiner/fuse
Trying to pull repository registry.fedoraproject.org/psteiner/fuse ... 
Trying to pull repository registry.access.redhat.com/psteiner/fuse ... 
Trying to pull repository docker.io/psteiner/fuse ... 
ERROR: Service 'smartgateway' failed to build: repository docker.io/psteiner/fuse not found: does not exist or no pull access
`

[log.txt](https://github.com/PatrickSteiner/IoT_Demo_Gateway/files/1142624/log.txt)

**Comment by PatrickSteiner** [comment]
It looks like the following steps from  `# ./build.sh` didn't work

echo "-- Building Fuse Image"
pushd .
cd Fuse
docker build --rm -t psteiner/fuse .
popd

can you please run 'docker build --rm -t psteiner/fuse .' from directory 'Fuse' manually to see what's causing this failure?

**Comment by mophahr** [comment]
It generates the following output:
```[*@fedora26 Fuse]$ docker build --rm -t psteiner/fuse .
Sending build context to Docker daemon  752.6MB
Step 1/20 : FROM psteiner/base
 ---> 7e014704a36c
Step 2/20 : MAINTAINER psteiner <psteiner@redhat.com>
 ---> Using cache
 ---> 7ffdfe4acb95
Step 3/20 : ENV FUSE_INSTALL_IMAGE jboss-fuse-karaf-6.3.0.redhat-187.zip
 ---> Using cache
 ---> 23854afc1750
Step 4/20 : ENV FUSE_INSTALL_DIR jboss-fuse-6.3.0.redhat-187
 ---> Using cache
 ---> 01dfe7706e49
Step 5/20 : ENV FUSE_LOCATION fuse
 ---> Using cache
 ---> 6b57a9a782a6
Step 6/20 : USER root
 ---> Using cache
 ---> 1f4a85e1f73a
Step 7/20 : WORKDIR $HOME
 ---> Using cache
 ---> 665524773020
Step 8/20 : ADD Docker_Files/software/$FUSE_INSTALL_IMAGE $HOME/tmp/
ADD failed: stat /var/lib/docker/tmp/docker-builder960579946/Docker_Files/software/jboss-fuse-karaf-6.3.0.redhat-187.zip: no such file or directory
```

Copying `jboss-fuse-karaf-6.3.0.redhat-187.zip` to `IoT_Demo_Gateway/Fuse/Docker_Files/software/` (previously, this directory only contained the file `fuse-integration-karaf-distro-1.7.0.redhat-630013.zip` linked to here  https://github.com/PatrickSteiner/IoT_Demo_Gateway#providing-red-hat-jboss-products) fixes this issue, and `docker build --rm -t psteiner/fuse .` now runs successfully.

$ ./build.sh` no does succeed, too.

**Comment by PatrickSteiner** [comment]
I fixed the download URL Thanks for pointing this out!
